### ISSUE TITLE
There is a typo in the `.ptb-2-3` rule 

### ISSUE THREAD

**Issue by thierryk** [nemophrost/atomic-css#2]
Line [#530](https://github.com/nemophrost/atomic-css/blob/master/bin/atomic.css#L530) reads:

``` css
.ptb-2-3 {
  padding-left: 6px;
  padding-bottom: 6px;
}
```

I believe that should be:

``` css
.ptb-2-3 {
  padding-top: 6px;
  padding-bottom: 6px;
}
```
